version: '3.8'
services: 
  postgres : 
    image: postgres:13
    container_name: ltdb-postgres
    restart: always
    ports : 
      - 5432:5432
    env_file: 
      - ./backend/.env
    volumes: 
      - postgres:/var/lib/postgresql/data

  rest:
    container_name: ltdb-rest
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports: 
      - 2008:2008
    env_file: 
      - ./backend/.env
    restart: always
    depends_on: 
      postgres:
        condition: service_started
      
volumes: 
  postgres:
    name: lantabur-database