version: '3.8'
services:
  
  # Reverse Proxy
  nginx: 
    image : nginx:mainline-alpine
    container_name: ltdb-nginx
    depends_on: 
      - rest 
      - postgres
    volumes : 
      - ./ltdb-nginx/nginx.conf:/etc/nginx/nginx.conf
    ports : 
      - 80:80

  frontend: 
    image : ltdb-frontend 
    container_name : ltdb-frontend
    build : 
      context : ./frontend
    depends_on: 
      - rest
    ports : 
      - 8080:80
    restart : on-failure
  
  # Database Postgres
  postgres : 
    image: postgres:13
    container_name: ltdb-postgres
    restart: always
    ports : 
      - 5432:5432
    env_file: 
      - ./backend/.env
    volumes: 
      - postgres:/var/lib/postgresql/data

  # Backend
  rest:
    container_name: ltdb-rest
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports: 
      - 2008:2008
    env_file: 
      - ./backend/.env
    restart: always
    depends_on: 
      postgres:
        condition: service_started

volumes: 
  postgres:
    name: lantabur-database